CREATE TABLE IF NOT EXISTS foods (
    id              INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    slug            TEXT NOT NULL UNIQUE,
    description     TEXT NOT NULL UNIQUE,
    verified        INTEGER DEFAULT 0,
    created_at      INTEGER DEFAULT (strftime('%s', 'now')),
    updated_at      INTEGER DEFAULT 0,
    image_id        INTEGER NOT NULL,
    source_id       INTEGER NOT NULL,
    glycemic_index  REAL NOT NULL,
    energy          REAL NOT NULL,
    carbohydrate    REAL NOT NULL,
    protein         REAL NOT NULL,
    fat             REAL NOT NULL,
    saturated_fat   REAL NOT NULL,
    trans_fat       REAL NOT NULL,
    sugar           REAL NOT NULL,
    fiber           REAL NOT NULL,
    cholesterol     REAL NOT NULL,
    sodium          REAL NOT NULL,
    potassium       REAL NOT NULL,
    water           REAL NOT NULL,
    iron            REAL NOT NULL,
    magnesium       REAL NOT NULL,
    calcium         REAL NOT NULL,
    zinc            REAL NOT NULL,
    vitamin_a       REAL NOT NULL,
    vitamin_b6      REAL NOT NULL,
    vitamin_b12     REAL NOT NULL,
    vitamin_c       REAL NOT NULL,
    vitamin_d       REAL NOT NULL,
    vitamin_e       REAL NOT NULL,
    vitamin_k       REAL NOT NULL
)