CREATE TABLE IF NOT EXISTS foods (
    id                      INT PRIMARY KEY AUTOINCREMENT NOT NULL,
    description             TEXT NOT NULL UNIQUE,
    image_id                INT NOT NULL,
    source_id               INT NOT NULL,
    glycemic_index          REAL NOT NULL,
    energy                  REAL NOT NULL,
    carbohydrate            REAL NOT NULL,
    protein                 REAL NOT NULL,
    fat                     REAL NOT NULL,
    cholesterol             REAL NOT NULL,
    sodium                  REAL NOT NULL,
    potassium               REAL NOT NULL,
    iron                    REAL NOT NULL,
    magnesium               REAL NOT NULL,
    calcium                 REAL NOT NULL,
    zinc                    REAL NOT NULL,
    vitamin_a               REAL NOT NULL,
    vitamin_b6              REAL NOT NULL,
    vitamin_b12             REAL NOT NULL,
    vitamin_c               REAL NOT NULL,
    vitamin_d               REAL NOT NULL,
    vitamin_e               REAL NOT NULL,
    vitamin_k               REAL NOT NULL
)