#[derive(Debug)]
struct Food {
    id: u32,
    description: String,
    image_url: String,
    source: String,
    tags: Vec<String>,
    allergens: Vec<String>,
    servings: HashMap<String, f32>,
    glycemic_index: f32,
    energy: f32,
    carbohydrate: f32,
    protein: f32,
    fat: f32,
    saturated_fat: f32,
    trans_fat: f32,
    sugar: f32,
    fiber: f32,
    cholesterol: f32,
    sodium: f32,
    potassium: f32,
    iron: f32,
    magnesium: f32,
    calcium: f32,
    zinc: f32,
    vitamin_a: f32,
    vitamin_b6: f32,
    vitamin_b12: f32,
    vitamin_c: f32,
    vitamin_d: f32,
    vitamin_e: f32,
    vitamin_k: f32
}